// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package incidents

import (
	"xaults-assignment/internal/services"
)

// Injectors from wire.go:

func NewIncidentWire() *IncidentController {
	incidentRepository := NewIncidentRepository()
	serviceRepository := services.NewServiceRepository()
	interfacesIncidentService := NewIncidentService(incidentRepository, serviceRepository)
	incidentController := NewIncidentController(interfacesIncidentService)
	return incidentController
}
