// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package services

// Injectors from wire.go:

func NewServiceWire() *ServiceController {
	serviceRepository := NewServiceRepository()
	serviceService := NewServiceService(serviceRepository)
	serviceController := NewServiceController(serviceService)
	return serviceController
}
