name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - name: Run golangci-lint
        continue-on-error: true
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          install-mode: goinstall

      - name: Run Unit Tests
        run: |
          go test -v -race ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t xaults-assignment:latest .

      - name: Verify Docker Image
        run: |
          docker images xaults-assignment
